server:
  port: 9090
spring:
  datasource:
    password: example
    platform: mysql
    url: jdbc:mysql://localhost:3306/jwt_authentication
    username: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
